spring:
  application:
    name: "Loja"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
  instances:
    realizarCompra:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8
