server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landson90/Config-Server-loja
          username: 
          password: 
          search-paths:
          - fornecedor
          